name: qmcpy
channels:
  - umontreal-simul
  - conda-forge
  - defaults
dependencies:
  - appmode=0.8.0
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.4
  - importlib_metadata=2.0.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - latnetbuilder=2.1.1
  - lcms2=2.11
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.0.0
  - libffi=3.2.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - llvm-openmp=11.0.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbclient=0.5.1
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - numexpr=2.7.1
  - olefile=0.46
  - openssl=1.0.2u
  - packaging=20.4
  - pandocfilters=1.4.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pyparsing=2.4.7
  - python=3.7.0
  - python-dateutil=2.8.1
  - python_abi=3.7
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - sqlite=3.28.0
  - testpath=0.4.4
  - tk=8.6.10
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - alabaster==0.7.12
    - attrs==19.3.0
    - babel==2.8.0
    - backcall==0.1.0
    - bleach==3.1.5
    - certifi==2020.4.5.1
    - cffi==1.14.0
    - chardet==3.0.4
    - codecov==2.1.5
    - commonmark==0.9.1
    - coverage==5.1
    - cryptography==3.2
    - dataclasses==0.6
    - docutils==0.16
    - future==0.18.2
    - idna==2.9
    - imagesize==1.2.0
    - importlib-metadata==1.6.0
    - iniconfig==1.1.1
    - ipykernel==5.2.1
    - ipython==7.14.0
    - jedi==0.17.0
    - jeepney==0.4.3
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - keyring==21.2.1
    - kiwisolver==1.2.0
    - markdown==3.2.2
    - matplotlib==3.2.1
    - more-itertools==8.4.0
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - notebook==6.1.5
    - numpy==1.18.5
    - pandas==1.0.3
    - pandoc==1.0.2
    - parso==0.7.0
    - pkginfo==1.5.0.1
    - pluggy==0.13.1
    - ply==3.11
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - py==1.8.2
    - pydeps==1.9.13
    - pygments==2.6.1
    - pyrsistent==0.16.0
    - pytest==6.2.1
    - pytz==2020.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - readme-renderer==26.0
    - recommonmark==0.6.0
    - requests==2.23.0
    - requests-toolbelt==0.9.1
    - scipy==1.4.1
    - secretstorage==3.1.2
    - six==1.14.0
    - snowballstemmer==2.0.0
    - sphinx==3.0.3
    - sphinx-markdown-tables==0.0.14
    - sphinx-math-dollar==1.1.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - stdlib-list==0.8.0
    - terminado==0.8.3
    - toml==0.10.2
    - torch==1.7.0
    - tornado==6.0.4
    - tqdm==4.46.1
    - traitlets==4.3.3
    - twine==3.1.1
    - typing-extensions==3.7.4.3
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - zipp==3.1.0
